POQTechProject/ApplicationCore/AppRepoServices/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using AppRepoServices.Areas.HelpPage.ModelDescriptions;

namespace AppRepoServices.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

POQTechProject/ApplicationCore/AppRepoServices/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using AppRepoServices.Areas.HelpPage.ModelDescriptions;
using AppRepoServices.Areas.HelpPage.Models;

namespace AppRepoServices.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

POQTechProject/ApplicationCore/AppRepoServices/Controllers/HomeController.cs
using DomainModels.Entities;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace AppRepoServices.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {

            return View();

        }
        public ActionResult GetAllProducts([FromUri] InputParameters inputParameters,String Apikey= "0c4bbda1-bf7b-479d-b619-83a1df21f4e7")
        {
            
            try
            {
                if (Apikey == ConfigurationManager.AppSettings["ApiKey"] || Apikey == ConfigurationManager.AppSettings["ApiKey2"])
                {
                    var client = new HttpClient();

                    var inputuri = ConfigurationManager.AppSettings["localhostURL"] + "?minprice=" + inputParameters.minprice + "&maxprice=" + inputParameters.maxprice + "&size=" + inputParameters.size + "&commonwords=" + inputParameters.commonwords + "&ApiKey=" + Apikey;
                    var response = client.GetAsync(inputuri).Result;
                    var products = response.Content.ReadAsAsync<IEnumerable<Products>>().Result;
                    ViewBag.count = products.Count();
                    return View(products);
                }
                else
                {
                    throw new Exception("Unathorised : " + "Please provide a valid key");
                }
            }
            catch(Exception ex)
            {
                
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                ViewBag.ErrorMessage = ex.Message;
                return View("~/Views/Shared/Error.cshtml"); 
                    
                    
                    }


        }
    }
}

POQTechProject/ApplicationCore/AppRepoServices/Controllers/ValuesController.cs
using DomainModels.Entities;
using Repository.Abstraction;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;

namespace AppRepoServices.Controllers
{
    public class ValuesController : ApiController
    {
        // GET api/values
        public IProductRepository repository;

        public ValuesController(IProductRepository _repository) : base()
        {
            repository = _repository;
        }


        public IEnumerable<Products> GetProducts([FromUri] InputParameters inputParameters)
        {

            try
            {

                return repository.GetAllProductsByInputValues(inputParameters);

            }

            catch (Exception ex)
            {
                throw;
            }
            }
            

        
    }
}

POQTechProject/ApplicationCore/AppRepoServices/Views/Home/GetAllProducts.cshtml
@model IEnumerable<DomainModels.Entities.Products>

@{
    ViewBag.Title = "GetAllProducts";
    var totalrecords = ViewBag.count;
    var counter = 0;
}
<script>
    var size = [];
    var apikey;
    window.onload = function (e) {
        console.log(@totalrecords);
        const queryString = window.location.search;
        const urlParams = new URLSearchParams(queryString);
        if (urlParams.get('minprice') != null) {
            document.getElementById("minprice").value = urlParams.get('minprice');
        }
        if (urlParams.get('maxprice') != null) {
            document.getElementById("maxprice").value = urlParams.get('maxprice');
        }
        if (urlParams.get('highlighttext') != null) {
            var Stringval = urlParams.get('highlighttext').split(",");
            console.log(Stringval);
            document.getElementById("highlighttext").value = urlParams.get('highlighttext');
           // for (var j = 0; j < Stringval.length; j++) {
            for (var i = 0; i < (@totalrecords-1); i++) {

                console.log(document.getElementById("des_" + i).innerText);
                for (var j = 0; j < Stringval.length; j++) {
                    if (document.getElementById("des_" + i).innerText.includes(Stringval[j]))  {
                        document.getElementById("des_" + i).innerHTML = document.getElementById("des_" + i).innerText.replace(Stringval[j], "<em>" + Stringval[j] + "</em>");
                    }
                }
             //   document.getElementById("des_" + i).innerHTML = document.getElementById("des_" + i).innerText;
                }
            //}
        }

        if (urlParams.get('size') != null) {
            urlParams.get('size').split(',').forEach(function (data) {
                size.push(data.toString());
                document.getElementById(data.toString()).checked = true;
            });
        }

    }
    
    function handleClick(cb) {
        if (cb.checked) {
            size.push(cb.value);
        } else {
            size.splice(size.indexOf(cb.value), 1);
        }

        console.log(size);
    }
    function searchProduct() {

        var url = "https://localhost:44367/Home/GetAllProducts";

        var paramUrl = [];
        if (document.getElementById("minprice").value > 0) {
            paramUrl.push("minprice");
        }
        if (document.getElementById("maxprice").value > 0) {
            paramUrl.push("maxprice");
        }

        if (document.getElementById("highlighttext").value.length >0) {
            paramUrl.push("highlighttext");
           
        }
        if (size.length > 0) {
            paramUrl.push("size");
        }
        paramUrl.push("apikey");
        if (paramUrl.length) {
            url = url+'?'
        }
        for (var i = 0; i < paramUrl.length > 0; i++) {
            if (paramUrl[i] != 'size') {
                url += paramUrl[i] + "=" + document.getElementById(paramUrl[i]).value+ '&'
            } else {
                url += paramUrl[i] + "=" + size.toString() + '&';
            }
        }
        if (paramUrl.length) {
            url = url.slice(0, (url.length - 1));
        }
        window.location.href = url;
    }
</script>
<h2>GetAllProducts</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table class="table">
    <tr>
        <th>
            <p>Sizes</p>
            <ul role="listbox" tabindex="0" aria-label="">
                <li tabindex="-1" role="option" aria-checked="false"><input type="checkbox" id="small" onclick='handleClick(this);' value="small" />Small</li>
                <li tabindex="-1" role="option" aria-checked="false"><input type="checkbox" id="medium" value="medium" onclick='handleClick(this);' />Medium</li>
                <li tabindex="-1" role="option" aria-checked="false"><input type="checkbox" id="large" value="large" onclick='handleClick(this);' />Large</li>

            </ul>
        </th>
        <input type="hidden" id="apikey" name="apikey" value="0c4bbda1-bf7b-479d-b619-83a1df21f4e7"/> 
        <th>
            <p>Prices</p>
            Min <input type="number" min="0" value="0" id="minprice" />
            Max <input type="number" min="0" value="0" id="maxprice" />
        </th>
        <th>
            <p>Highlight</p>
            Text : <input type="text"  value="" id="highlighttext" />
            
        </th>

        <th>
            <button onclick="searchProduct()">Search</button>
        </th>
    </tr>
    </table>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.sizes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th></th>
    </tr>


    @{
        int counter1 = 0;
        foreach (var item in Model)
        {


            <tr>


                <td>
                    @Html.DisplayFor(modelItem => item.title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.sizes)
                </td>
                <td id="des_@counter1">

                    @Html.DisplayFor(modelItem => item.description)
                </td>
               
            </tr>
                counter1 = counter1 + 1;

            }
        }

    </table>
              

POQTechProject/ApplicationCore/AppRepoServices/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2> Welcome to Product Repository </h2>

POQTechProject/ApplicationCore/AppRepoServices/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>